### ISSUE TITLE
Add an explicit conversion operator between 2 types

### ISSUE THREAD

**Issue by ignatandrei** [Ohorodnikov/AutoDto#13]
When generating, please add an automatic conversion operator

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/user-defined-conversion-operators

to can automatically convert from a type to another .

It will be more cool as an example , instead of having 
```csharp
using AutoDTODemo;

var d = new Department();
d.Name = "IT";
d.ID = 1;
d.Employees=new Employee[] { new Employee() };

var dto= new DepartmentDTO();
//it will be beneficial if it will have also a constructor
//for transfer properties
dto.Name = d.Name;
dto.ID = d.ID;
```
I could have this
```csharp
using AutoDTODemo;

var d = new Department();
d.Name = "IT";
d.ID = 1;
d.Employees=new Employee[] { new Employee() };

var dto= d as DepartmentDTO();

```

( full example at https://ignatandrei.github.io/RSCG_Examples/v2/docs/AutoDTO#example--source-csproj-source-files-)

**Comment by Ohorodnikov** [comment]
Thanks for your idea. 

Mapping DTOs to BLs is a common task and may be not as simple as expected. You can use any libs for mapping, like [AutoMapper](https://github.com/AutoMapper/AutoMapper), [Mapster](https://github.com/MapsterMapper/Mapster), etc.

I have some plans somewhere in the future to create own mapper using source gen, but not now.

Thanks for contibuting to AutoDto.
